name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  upload:
    needs: release
    strategy:
      matrix:
        name: [
          linux,
          windows,
          macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/msmd
            asset_name: msmd-linux-${{ github.ref_name }}
          - name: windows
            os: windows-latest
            artifact_name: target/release/msmd.exe
            asset_name: msmd-windows-${{ github.ref_name }}.exe
          - name: macos
            os: macos-latest
            artifact_name: target/release/msmd
            asset_name: msmd-macos-${{ github.ref_name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: cargo build --release --locked

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream